name: Azure Web App Deployment (Python)

on:
  push:
    branches:
      - main  # o la rama que utilices para hacer deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del código
    - name: Checkout code
      uses: actions/checkout@v3  # Actualizado a v3

    # 2. Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v3  # Actualizado a v3
      with:
        python-version: '3.9'

    # 3. Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Build (opcional, si necesitas alguna tarea previa al despliegue)
    - name: Run tests (opcional)
      run: |
        pytest  # Si tienes pruebas, este es el lugar adecuado para ejecutarlas

    # 5. Deploy a Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'my-app-service'  # Reemplaza con el nombre de tu app service en Azure
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Agrega tu archivo de perfil de publicación en Secrets
        package: '.'  # Este es el directorio que se va a desplegar (ajústalo si es necesario)
